# This is a basic workflow that is manually triggered

name: test script

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      baseurl:
        description: "Base URL"
        default: "https://github.com"
        required: true
        type: string
env:
  DAY_OF_WEEK: ${{github.event.inputs.baseurl}}
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Generate app
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
          channel: "stable"
      - run: dart pub global activate melos
      - run: melos run:buyer -- samp #${{github.event.inputs.baseurl}}
